### ISSUE TITLE
Battery Connector Polarity is Labeled Incorrectly on PCB

### ISSUE THREAD

**Issue by abrahamjsimpson** [verlab/hero_common#19]
We are using version 2.6. Looking at the PCB design (board.brd), I noticed that between the connector where the battery is plugged in and the header for the left encoder there is silkscreen text (on layer 25, tNames) that says "VCC GND" (see screenshot).
![Mislabeled Battery connector](https://user-images.githubusercontent.com/43624452/221710765-a40bdc61-06fa-476e-8378-27bb56707855.JPG)
It seems that this label is intended for the battery connector; however, if so, they are reversed! As the screenshot shows, ground is actually on the _left_ and VCC is on the _right_. This should be fixed.

**Comment by rezeck** [comment]
Hey @abrahamjsimpson,

Thank you for reporting this issue. 

I incorporated this modification in the 2.7 version of the board.

![image](https://user-images.githubusercontent.com/14208261/222995352-abbe5195-e1e7-479e-8eed-f904dcfb66cb.png)
![image](https://user-images.githubusercontent.com/14208261/222995367-10fb5d7d-ae37-4950-bc22-5ea4b4256f9d.png)

Best,
Rezeck

**Comment by abrahamjsimpson** [comment]
Thank you!
