### ISSUE TITLE
gazebo algorithm issue

### ISSUE THREAD

**Issue by besobees** [verlab/hero_common#33]
Hello @rezeck,

We've tested your impressive GRF-based collective transport algorithm, but unfortunately, it seems to be ineffective. When the robots detect the target, they all converge on it regardless of the presence of objects. Could you please send us the updated files?

Additionally, we've constructed your Hero 2.0v robot and would like to implement the algorithm on this model.

Looking forward to your response.

**Comment by rezeck** [comment]
Hi @besobees 

It's fantastic to hear that you've constructed the Hero robot! We're always thrilled to see our work coming to life. If you have any images or feedback to share, please don't hesitate to do so. We greatly value input from our community of contributors.

As for the issue with the GRF-based collective transport algorithm, I'd recommend revisiting the initial issue description on our GitHub repository at https://github.com/rezeck/grf_transport/issues/1. If the issue persists and it's related to the code within this repository, we can continue troubleshooting it here.

Looking forward to resolving this matter with you.

Best regards,
Rezeck

**Comment by besobees** [comment]
i will send you my problem here https://github.com/rezeck/grf_transport/issues/1 take a look @rezeck <3

**Comment by rezeck** [comment]
Solved #33 in https://github.com/rezeck/grf_transport/issues/1
